services:
  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_scraper
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=8000
    networks:
      - app-network
    command: python app.py
    restart: always
  
networks:
  app-network:
    driver: bridge