services:
  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_scraper
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    networks:
      - app-network
    command: python app.py

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    networks:
      - app-network
    deploy:
      replicas: 3
    command: rq worker --url redis://redis:6379 default

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_scheduler
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    networks:
      - app-network
    command: python -m rq_scheduler

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    networks:
      - app-network
  
networks:
  app-network:
    external: true
