version: "3.8"
services:
  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_scraper
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - app-network
networks:
  app-network:
    name: app-network
    driver: bridge